package com.patent.evaluator.constant;

public interface AuthorityCodes {
    String VIEW_LOOKUP_VALUE_MANAGEMENT = "VIEW_LOOKUP_VALUE_MANAGEMENT";
    String CREATE_LOOKUP_VALUE = "CREATE_LOOKUP_VALUE";
    String UPDATE_LOOKUP_VALUE = "UPDATE_LOOKUP_VALUE";
    String DELETE_LOOKUP_VALUE = "DELETE_LOOKUP_VALUE";
    String VIEW_USER_MANAGEMENT = "VIEW_USER_MANAGEMENT";
    String UPDATE_AUTHORITY = "UPDATE_AUTHORITY";
    String VIEW_AUTHORITY_MANAGEMENT = "VIEW_AUTHORITY_MANAGEMENT";
    String UPDATE_ROLE_AUTHORITIES = "UPDATE_ROLE_AUTHORITIES";
}
